language: go
sudo: required
dist: trusty

go:
  - 1.12

services:
- docker

before_install:
  - sudo apt-get update 
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install docker-ce
  - sudo apt-get install golang -y
  - docker version
  - curl -s https://packages.confluent.io/deb/5.2/archive.key | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/5.2 stable main"
  - sudo apt-get update

install:
- sudo apt-get install dnsmasq python librdkafka-dev -y
- sudo pip install botocore
- sudo sed -i "$ a\address=/.s3.test.com/10.5.0.18" /etc/dnsmasq.conf
- sudo sed -i "$ a\address=/.s3-internal.test.com/10.5.0.18" /etc/dnsmasq.conf
- sudo service dnsmasq restart
- sudo sed -i "1 i\nameserver 127.0.0.1" /etc/resolv.conf
- sudo ufw disable

script:
- make integrate
- export GO111MODULE=on
  # golang 1.12 will change the permission of go.mod and go.sum
  # use chmod to reset the permission of go.mod and go.sum to make go test happy
- sudo chmod 644 go.mod go.sum
- sudo python test/sanity.py
- pushd test/go
- go test -v
- popd
- cat lc.log
- pushd messagebus/tests
- go test -check.vv
- popd

before_deploy:
  - echo "prepare package1"
  - sudo make pkg
  - sudo make image

deploy:
  - provider: releases
    api_key: $GithubToken
    file: $TRAVIS_BUILD_DIR/yig*.x86_64.rpm
    file_glob: true 
    skip_cleanup: true
    on:
      repo: richard1999/yig
      tags: true

